### ISSUE TITLE
All nodezoo services need to have working Dockerfiles

### ISSUE THREAD

**Issue by AdrianRossouw** [nodezoo/nodezoo-system#15]
For us to be able to deploy nodezoo on AWS the way we want to, we need to have all the services built using containers.

I have already converted some of the services to working containers, but we need to manually test and confirm that all of them build and run via docker and docker-compose.

The task is as follows :
1. set up docker locally, and have it running via  
   `eval $(docker-machine env default)`
2. go through each of the [services defined in the package.json](https://github.com/nodezoo/nodezoo-system/blob/master/package.json)
3. Make sure the docker container has one of the following variations
   1. if the service is backend only, base it on the [nodezoo-base dockerfile](https://github.com/nodezoo/nodezoo-base/blob/live/Dockerfile)
   2. if it has an http service, base it on the [nodezoo-web dockerfile](https://github.com/nodezoo/nodezoo-base/blob/live/Dockerfile)
      1. HTTP services should have `RUN npm run build` in their Dockerfiles.
      2. HTTP services should `EXPOSE $port` on the same port the service listens to  
         (check the code).
4. All services should have a `CMD ...` taken from the [fuge-config.js file](https://github.com/nodezoo/nodezoo-system/blob/master/fuge/fuge-config.js).
5. Remove the overrides once they are in the dockerfiles  
   (fuge should pick up the run command from the dockerfile automatically)
6. To test if the container builds correctly, cd into the directory and run  
   `docker build -t some-service .`
7. Once everything is done, you should be able to run this from the nodezoo-system folder :  
   `docker-compose -f fuge/services.yml build`

**Comment by mcdonnelldean** [comment]
@AdrianRossouw I think we are good on this?

**Comment by mcdonnelldean** [comment]
Closed as complete.
