### ISSUE TITLE
GitHub key needs to be easier to insert

### ISSUE THREAD

**Issue by mcdonnelldean** [nodezoo/nodezoo-system#18]
Right now to insert the github api key we have to go into the module and paste it there. It needs to be something that we can drop in and ignore so that it doesn't get checked it.

Thoughts @AdrianRossouw 

The module in question is nodezoo-github, it can currently read it via an env variable.

**Comment by AdrianRossouw** [comment]
Just set it up in the *.yml ?

Also you could add an env_file.
1. in the service
   `env_file: ../system.env`
2. add that file to .gitignore
3. make a system.env.sample with some default settings.
4. instruct them to copy the file during install

**Comment by mcdonnelldean** [comment]
@AdrianRossouw Won't work because of fuge. Simple solution for now is directly in system.yml
