### ISSUE TITLE
Issues when installing the system from scratch

### ISSUE THREAD

**Issue by vislamov** [nodezoo/nodezoo-system#20]
## Summary

Below the list of issues I've faced installing nodezoo-system on a new computer.
### Node version

Some modules require node >=5,  needed to switch to node 5 before running `npm install`.
### Warnings

```
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated redux@3.0.6: Versions before 3.1.3 are known to crash on IE in some cases. Please update to 3.1.3 or newer.
```

```
npm WARN prefer global mimer@0.2.1 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
```
### Required modules for successful build

In order to build the local system has to have `webpack` and `copyfiles` installed. 

```
npm install -g webpack
```

```
npm install -g copyfiles
```
### Errors

The common error message during the build:

```
mkdir: /src: Permission denied
```
### Metrics

```
process exit [48988]: metrics
client error: 5432 -> 192.168.99.100:5432 => ECONNREFUSED
```
### Concorda

```
process exit [38102]: concorda
```

Concorda process exited after complaining several times:

```
client error: 8086 -> 192.168.99.100:8086 => ECONNREFUSED
please retry operation
```
#### Concorda PostgreSQL config

I've included `postgres` config in `system.yml` as follows 

```
pgdata:
  image: postgres
  container_name: pgdata
  command: /bin/true
  volumes:
    - /var/lib/postgresql/data

postgres:
  image: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=concorda
    - POSTGRES_PASSWORD=concorda
  volumes_from:
    - pgdata
```

After config change Concorda is running but both `pgdata` and `postgres` processes are quitting.

Server log:

```
Unable to find image 'postgres:latest' locally
Pulling repository docker.io/library/postgres
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/postgres/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
```

Pulled postgres image manually via `docker pull postgres` both processes still quitting: 

Server log:

```
docker: Error response from daemon: No such container: pgdata.
See 'docker run --help'.
```

Installed Concorda in separate location and run as microservice, according to this [instuctions](https://github.com/Concorda/docs/blob/master/doc/install-concorda-microservice.md).

Now only `pgdata` process is quitting after the start, no server logs for `pgdata`. 
### Concorda

Unable login.

Server response:

```
app.js:31280 POST http://localhost:3050/auth/login 404 (Not Found)
```

Routing info is below. Do we miss PROXY_HOST and PROXY_PORT values? 

```
server.route({
      method: '*',
      path: '/auth/{path*}',
      handler: {
        proxy: {
          passThrough: true,
          redirects: 5,
          mapUri: function(req, cb) {
            var uri = {
              protocol: 'http',
              hostname: process.env.PROXY_HOST,
              port: process.env.PROXY_PORT,
              pathname: req.params.path
            };
            cb(null, url.format(uri));
          }
        }
      }
});
```

Server log:

```
[concorda - 55209]: Debug: handler, error 
    {"msec":0.8037450015544891,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}}
```
### Vidi

Unable to login.

Server response:

```
{
   "http$":{
      "status":200
   },
   "ok":false,
   "why":{
      "eraro":true,
      "orig":null,
      "code":"act_not_found",
      "seneca":true,
      "package":"seneca",
      "msg":"seneca: No matching action pattern found for { nick: 'admin@email.com',  email: 'admin@email.com',  password: 'admin',  role: 'user',  cmd: 'login' }, and no default result provided (using a default$ property).",
      "details":{
         "args":"{ nick: 'admin@email.com',  email: 'admin@email.com',  password: 'admin',  role: 'user',  cmd: 'login' }",
         "plugin":{

         }
      },
      "callpoint":"at Object.execute_action [as fn] (/Users/vlad/Documents/Dev/nodezoo-system/node_modules/vidi-dashboard/node_modules/chairo/node_modules/seneca/seneca.js:1054:29)"
   }
}
```

**Comment by mcdonnelldean** [comment]
Add em all here, I'm cleaning this up over the weekend so I can bring in your notes.

**Comment by mcdonnelldean** [comment]
@vislamov This is great stuff, following on from this, I've made a couple of changes,

1: Vidi and Concorda are no longer included, they will be added back when they are working.
2: Dockered services that need volumes have been removed until they are working.
3: Node 5 was due to `toolbag`, the author has resolved this we just need to update our services
4: `mkdir: /src: Permission denied` should be resolved now
5: Global installs should be fixed now also (you shouldn't need these installed)

**Comment by vislamov** [comment]
Everything works now. All processes are running. The only thing that `influx` is complaining in the console when system starts:

```
client error: 8086 -> 192.168.99.100:8086 => ECONNREFUSED
please retry operation
```

**Comment by timoweiss** [comment]
@vislamov @mcdonnelldean I'm having the same issue with the `ECONNREFUSED` error.
`nodezoo_metrics` is the complaining module since it wants to connect to the influxdb :)

**Comment by mcdonnelldean** [comment]
@vislamov @timoweiss I'm fixing this today, we are going to pull influx and vidi for now and focus on getting Nodezoo live. I've a couple of updates to make today and then it should be lovely jubly to play around with. (I've been on other things so only getting to it now)

**Comment by timoweiss** [comment]
@mcdonnelldean many thanks! :) you are doing a great job!

**Comment by vislamov** [comment]
Great, it actually not bothering me much, but anyway it's good to have a clean system running.

**Comment by mcdonnelldean** [comment]
Should be all good now.
