### ISSUE TITLE
nodezoo-github unable to authenticate

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-system#26]
Just a PSA to say that if you run into this issue, and have set your token according to the docs in `system.env`, make sure you pull the latest version of Fuge

I blew away my setup to QA test Dean's changes, and everything looks good

**Comment by mcdonnelldean** [comment]
Good spot,

@shanel262 we should document how to add this and also the minimum version of fuge required to run. This will be your next task.

**Comment by mcdonnelldean** [comment]
@shanel262 You lucky duck! @Georgette has done the hard work for you, you just need to add minimum fuge version.

**Comment by shanel262** [comment]
@mcdonnelldean It's a lucky Monday! Thanks @Georgette! I'll get on this :)
