### ISSUE TITLE
High-Level Diagram for Onboarding

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-system#43]
We could really use a high-level diagram on how all the services communicate, and basically all the moving parts of the system. I'd even include seneca patterns, and transport methods for training purposes. One of the huge hurdles I had at the meet up was system visualization (and I did have a diagram, but wish it was more detailed!).

**Comment by mcdonnelldean** [comment]
Fully agree. I think I should at least do the first draft as I'm in the best position to say how it should be 😂

**Comment by matt-oc** [comment]
I like this idea alot 😄

**Comment by mirceaalexandru** [comment]
I hope is accurate:

https://github.com/nodezoo/nodezoo-docs/blob/master/doc/architecture.md

I will close this issue for now.
