### ISSUE TITLE
Refine published content

### ISSUE THREAD

**Issue by mihaidma** [nodezoo/nodezoo-system#51]
Currently we publish all files from the services. We should add a "files" section in package.json in which describe explicitly what should be published on npm:

```
 "files": [
    "README.md",
    "LICENSE.txt",
    "lib",
...
    "package.json"
  ],
```

**Comment by mcdonnelldean** [comment]
Agreed, there are instances where we can make the npm publish much smaller by excluding things like tests et al.

**Comment by shanel262** [comment]
@mihaidma Close?
