### ISSUE TITLE
verify packages in dependencies and devDependencies

### ISSUE THREAD

**Issue by mihaidma** [nodezoo/nodezoo-system#53]
Verify that package dependecies are correctly put in dependencies and devDependencies categories at all nodezoo services.

**Comment by shanel262** [comment]
- [x] Nodezoo-base https://github.com/nodezoo/nodezoo-base/pull/20
- [x] Nodezoo-coveralls
- [x] Nodezoo-dequeue https://github.com/nodezoo/nodezoo-dequeue/pull/10
- [x] Nodezoo-github https://github.com/nodezoo/nodezoo-github/pull/87
- [x] Nodezoo-info https://github.com/nodezoo/nodezoo-info/pull/64
- [x] Nodezoo-npm https://github.com/nodezoo/nodezoo-npm/pull/87
- [x] Nodezoo-search https://github.com/nodezoo/nodezoo-search/pull/50
- [x] Nodezoo-travis
- [x] Nodezoo-updater
- [x] Nodezoo-web

**Comment by CodeWriterWriter** [comment]
https://github.com/nodezoo/nodezoo-updater/pull/23

**Comment by CodeWriterWriter** [comment]
https://github.com/nodezoo/nodezoo-travis/pull/52

**Comment by CodeWriterWriter** [comment]
https://github.com/nodezoo/nodezoo-travis/pull/52

**Comment by shanel262** [comment]
@mihaidma Can I close?
